# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 413)
        MainWindow.setStyleSheet("background-color: #524b4b;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.play = QtWidgets.QPushButton(self.centralwidget)
        self.play.setGeometry(QtCore.QRect(90, 10, 291, 81))
        self.play.setStyleSheet("QPushButton{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #7d7a7a;\n"
"\n"
"    border: 4px solid #fc8383;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #fc8383;\n"
"\n"
"    color: black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #ff4545;\n"
"\n"
"    color: black;\n"
"\n"
"}")
        self.play.setObjectName("play")
        self.stop = QtWidgets.QPushButton(self.centralwidget)
        self.stop.setGeometry(QtCore.QRect(90, 100, 291, 81))
        self.stop.setStyleSheet("QPushButton{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #7d7a7a;\n"
"\n"
"    border: 4px solid #fc8383;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #fc8383;\n"
"\n"
"    color: black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #ff4545;\n"
"\n"
"    color: black;\n"
"\n"
"}")
        self.stop.setObjectName("stop")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(90, 190, 291, 81))
        self.select.setStyleSheet("QPushButton{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #7d7a7a;\n"
"\n"
"    border: 4px solid #fc8383;\n"
"\n"
"    color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::hover{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #fc8383;\n"
"\n"
"    color: black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QPushButton::pressed{\n"
"\n"
"    border-radius: 20px;\n"
"\n"
"    background-color: #ff4545;\n"
"\n"
"    color: black;\n"
"\n"
"}")
        self.select.setObjectName("select")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 290, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.volume = QtWidgets.QSlider(self.centralwidget)
        self.volume.setGeometry(QtCore.QRect(10, 330, 431, 22))
        self.volume.setOrientation(QtCore.Qt.Horizontal)
        self.volume.setObjectName("volume")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.play.setText(_translate("MainWindow", "PushButton"))
        self.stop.setText(_translate("MainWindow", "PushButton"))
        self.select.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Гучність"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
